---
# tasks file for ansible-node-deploy/
- name: Ensure group "admin" exists
  group:
    name:   admin
    state:  present

- name: Create `ansible` user
  user:
    name="ansible"
    home="/home/ansible"
    shell="/bin/bash"
    append="true"
    group="admin"
    comment="ansible"

- name: Set up authorized_key
  authorized_key:
    key="{{lookup('file', '~/.ssh/id_rsa.pub')}}"
    user="ansible"
    manage_dir=no

- name: allow sudo without password for ansible user
  copy:
    src: ansible
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: 0644
